### ISSUE TITLE
Error running node /create-profile/create-up.js - Error.captureStackTrace(err, this);

### ISSUE THREAD

**Issue by tantodefi** [lukso-network/lukso-playground#15]
After git cloning repo I made me EOA and successfully funded it with "LYXt' but when trying to programatically `create-up.js` i get the following error: 

```
node:internal/deps/undici/undici:13220
    Error.captureStackTrace(err, this);
          ^

TypeError: RequestInit: duplex option is required when sending a body.
    at Object.fetch (node:internal/deps/undici/undici:13220:11)
    at async Client.fetch (lukso-playground/node_modules/ipfs-utils/src/http.js:129:22)
    at async addAll (lukso-playground/node_modules/ipfs-http-client/src/add-all.js:40:17)
    at async last (lukso-playground/node_modules/it-last/index.js:13:20)
    at async Object.add (lukso-playground/node_modules/ipfs-http-client/src/add.js:23:14)
    at async ipfsUpload (lukso-playground/node_modules/@lukso/lsp-factory.js/build/main/src/lib/helpers/uploader.helper.js:99:12)
    at async UniversalProfile.uploadProfileData (lukso-playground/node_modules/@lukso/lsp-factory.js/build/main/src/lib/classes/universal-profile.js:131:30)
    at async getLsp3ProfileDataUrl (lukso-playground/node_modules/@lukso/lsp-factory.js/build/main/src/lib/services/universal-profile.service.js:140:27)
    at async getEncodedLSP3ProfileData (lukso-playground/node_modules/@lukso/lsp-factory.js/build/main/src/lib/services/universal-profile.service.js:148:38)

Node.js v20.8.0
```

I did find [this](https://github.com/nodejs/node/issues/46221) however I'm unsure how to go about implement this fix...

Has anyone else ran into this issue? Thanks in advance for your help!

**Comment by richtera** [comment]
This sounds like a 'method' problem I.e. GET instead of POST

**Comment by MattPereira** [comment]
I had the same duplex TypeError on node v18.18.2

I think the the `@lukso/lsp-factory.js` package is incompatible with anything above node v16.x.x

![image](https://github.com/lukso-network/lukso-playground/assets/73561520/e64a26b4-138e-49f2-8fe0-1c09b70fc271)


![image](https://github.com/lukso-network/lukso-playground/assets/73561520/c9450b6c-6ddd-4932-9864-74389d4bdacf)

**Comment by tantodefi** [comment]
Thanks @MattPereira! This works!
